spring:
  main:
    log-startup-info: false
    banner-mode: off

  sql:
    init.mode: always

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password



logging.level.org.zalando.logbook: TRACE